name: Run rspec

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run rspec
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
