name: Ruby_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd api
          bundle _2.4.14 install

      - name: Run tests
        run: |
          cd api
          bundle exec rspec

      - name: Run rubocop
        run: |
          cd api
          bundle exec rubocop
